<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MainStation" Id="{aba662ba-0104-0d8c-3ede-cc6ee7a38896}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MainStation EXTENDS TcoCore.TcoObject
//VAR
//    turckRfidHead : RfidHead(THIS^, T#1MS);
//    sUId          : T_MaxString;
//END_VAR
//VAR
//	    _uid          : BOOL;
//END_VAR

VAR
    rfidHead_Test : RfidHead_Test;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>