<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{dd7b1ca3-48b8-4b4b-827b-c46336d569fa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    _app : AppContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_app.Run();
_app.RtcSynchronize(true, '', 60);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>